//! `cargo strata init`: write a config that describes the workspace as it is
//! now, so a first run is clean and each later change to an edge shows up.

use crate::config::Config;
use crate::modules::observe_crate;
use cargo_metadata::{DependencyKind, Metadata};
use std::collections::{BTreeMap, BTreeSet, HashSet};
use std::path::PathBuf;

fn q(s: &str) -> String {
    toml::Value::String(s.to_string()).to_string()
}

fn list(items: &BTreeSet<String>) -> String {
    format!(
        "[{}]",
        items.iter().map(|s| q(s)).collect::<Vec<_>>().join(", ")
    )
}

/// Config text allowing exactly the crate edges and module references that
/// exist now. `verus` also marks every crate `verus = true`.
pub fn generate(meta: &Metadata, verus: bool, verus_feature: bool) -> (String, Vec<String>) {
    let ws_root: PathBuf = meta.workspace_root.clone().into();
    let members: HashSet<_> = meta.workspace_members.iter().collect();
    let pkgs: Vec<_> = meta
        .packages
        .iter()
        .filter(|p| members.contains(&p.id))
        .collect();
    let names: BTreeSet<String> = pkgs.iter().map(|p| p.name.to_string()).collect();
    let cfg = Config {
        skip_cfg_test: true,
        resolve: true,
        ..Config::default()
    };
    let mut out = String::from(
        "# Generated by `cargo strata init`: the crate and module edges that exist now.\n\
         check_dev = true\n\n",
    );
    let mut errors = Vec::new();
    let mut sorted: Vec<_> = pkgs.clone();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));
    for pkg in sorted {
        let mut allow = BTreeSet::new();
        let mut allow_dev = BTreeSet::new();
        for d in &pkg.dependencies {
            if !names.contains(&d.name) {
                continue;
            }
            match d.kind {
                DependencyKind::Development => allow_dev.insert(d.name.clone()),
                _ => allow.insert(d.name.clone()),
            };
        }
        allow_dev.retain(|d| !allow.contains(d));
        out.push_str(&format!(
            "[[crate]]\nname = {}\nallow = {}\n",
            q(&pkg.name),
            list(&allow)
        ));
        if !allow_dev.is_empty() {
            out.push_str(&format!("allow_dev = {}\n", list(&allow_dev)));
        }
        if verus {
            out.push_str("verus = true\n");
        }
        let roots: Vec<PathBuf> = pkg
            .targets
            .iter()
            .filter(|t| {
                t.kind.iter().any(|k| {
                    matches!(
                        k.to_string().as_str(),
                        "lib" | "proc-macro" | "bin" | "rlib"
                    )
                })
            })
            .map(|t| t.src_path.clone().into())
            .collect();
        let (graph, errs) = observe_crate(&roots, &cfg, verus && verus_feature, &ws_root);
        errors.extend(errs);
        let graph: BTreeMap<_, _> = graph.into_iter().collect();
        for (m, deps) in graph {
            out.push_str(&format!(
                "\n[[crate.module]]\npath = {}\ndepends_on = {}\n",
                q(&m),
                list(&deps)
            ));
        }
        out.push('\n');
    }
    (out, errors)
}
